# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pumaplot',
                'doc_host': 'https://.github.io',
                'git_url': 'https://github.com//pumaplot',
                'lib_path': 'pumaplot'},
  'syms': {'pumaplot.core': {'pumaplot.core.foo': ('core.html#foo', 'pumaplot/core.py')}}}
